devices:
 Nexus5:
  caps:
   deviceName: "Nexus5"
   platformName: "Android"
   version: "8.0.0"
   app: "C:/Users/Alef Rodrigues/Desktop/Appium_camila/exemplo_appium"
   appPackage: "br.com.ftec.ailton.cadastrodecarrosweb"
   appActivity: "br.com.ftec.ailton.cadastrodecarrosweb.MainActivity"
   newCommandTimeout: "3600"
   port: 4724
   appium_port: 4724
   appium_lib: { wait: 20, debug: false}
#  Iphone6:
#   caps:
#    deviceName: "Nexus5"
#    platformName: "Android"
#    version: "8.0.0"
#    app: "C:/Users/Alef Rodrigues/Desktop/Appium_camila/exemplo_appium"
#    appPackage: "br.com.ftec.ailton.cadastrodecarrosweb"
#    appActivity: "br.com.ftec.ailton.cadastrodecarrosweb.MainActivity"
#    newCommandTimeout: "3600"
#    port: 4724
#    appium_port: 4724
#    appium_lib: { wait: 20, debug: false}

# suellenlleao [4:10 PM] 
# devices:
# Motorola:
#  caps:
#   deviceName: "Motorola"
#   platformName: "Android"
#   version: "7.1.1"
#   app: "C:/artefatos_inlab/appium_exemplos/features/support/ApkProvaCarros.apk"
#   appPackage: "br.com.ftec.ailton.cadastrodecarrosweb" #o apk deve estar aberto para executatr o comando
#   appActivity: "br.com.ftec.ailton.cadastrodecarrosweb.MainActivity" #o apk deve estar aberto para executatr o comando
#   newCommandTimeout: "3600"
#   port: 4723
#   appium_port: 4723
#   appium_lib: { wait: 20, debug: false}